sdr_profile = {0: {'system_scenario': '4G5GSISO-TU',
                   'diagnostic': 1,
                   'wireless_channel': 'Fading',
                   'channel_band': 0.97 * 960e3,
                   'bin_spacing': 15e3,
                   'channel_profile': 'LTE-TU',
                   'CP_type': 'Normal',
                   'num_ant_txrx': 1,
                   'param_est': 'Estimated',
                   'MIMO_method': 'SpMult',
                   'SNR': 5,
                   'ebno_db': [24],
                   'num_symbols': [512],
                   'stream_size': 1}, 1: {'system_scenario': 'WIFIMIMOSM-A',
                                          'diagnostic': 0,
                                          'wireless_channel': 'Fading',
                                          'channel_band': 0.9 * 20e6,
                                          'bin_spacing': 312.5e3,
                                          'channel_profile': 'Indoor A',
                                          'CP_type': 'Extended',
                                          'num_ant_txrx': 2,
                                          'param_est': 'Ideal',
                                          'MIMO_method': 'SpMult',
                                          'SNR': 50,
                                          'ebno_db': [6, 7, 8, 9, 10, 14, 16, 20, 24],
                                          'num_symbols': [10, 10, 10, 10, 10, 10, 10, 10, 10],
                                          'stream_size': 2}}
