INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_OFDMTRANSMITTER OFDMTransmitter)

FIND_PATH(
    OFDMTRANSMITTER_INCLUDE_DIRS
    NAMES OFDMTransmitter/api.h
    HINTS $ENV{OFDMTRANSMITTER_DIR}/include
        ${PC_OFDMTRANSMITTER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    OFDMTRANSMITTER_LIBRARIES
    NAMES gnuradio-OFDMTransmitter
    HINTS $ENV{OFDMTRANSMITTER_DIR}/lib
        ${PC_OFDMTRANSMITTER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OFDMTRANSMITTER DEFAULT_MSG OFDMTRANSMITTER_LIBRARIES OFDMTRANSMITTER_INCLUDE_DIRS)
MARK_AS_ADVANCED(OFDMTRANSMITTER_LIBRARIES OFDMTRANSMITTER_INCLUDE_DIRS)

