/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-utsa_ofdm
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_UTSA_OFDM_API_H
#define INCLUDED_UTSA_OFDM_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_utsa_ofdm_EXPORTS
#define UTSA_OFDM_API __GR_ATTR_EXPORT
#else
#define UTSA_OFDM_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_UTSA_OFDM_API_H */
